bind r source-file ~/.config/tmux/tmux.conf

set -g mode-keys vi
set -g status-keys vi

set -g allow-rename off

set -g base-index 1
set -g display-time 3000
set -g history-limit 25000
set -s default-terminal 'screen-256color'

set -g status-position top
set -g status-right '%H:%M %Y-%m-%d'

# Neovim stuff (from :checkhealth)
set-option -sg escape-time 10
set-option -g focus-events on
set-option -sa terminal-features ',alacritty:RGB'
