install:
	@echo "Coping engi script to /usr/local/bin..."
	cp ./main.sh /usr/local/bin/engi
	chmod 755 /usr/local/bin/engi

uninstall:
	@echo "Removing engi script from /usr/local/bin..."
	rm /usr/local/bin/engi
